### ISSUE TITLE
Map support for configuration types

### ISSUE THREAD

**Issue by bagdemir** [bagdemir/propane#4]
The users can use map types as configurations. 

```
EU: 
   routing:
      eu: "eu.foo.com"
      us:  "us.foo.com"
```

should mapped to

```
Map<String, String> routing;
```

We should create a new annotation type for the map configurations.
